import type { DashboardData, OnboardingInput, UploadedFileRecord } from "@/types/domain";

const uploadedMeetSheet: UploadedFileRecord = {
  id: "file-1",
  fileName: "league-finals-results.png",
  mimeType: "image/png",
  sizeBytes: 284991,
  kind: "meet-results",
  createdAt: "2026-03-26T16:42:00.000Z",
  summary:
    "Looks like a meet results screenshot with 50 free 25.29 and 100 free 55.88 highlighted.",
  extractedEntries: [
    { event: "50 free", time: "25.29", confidence: 0.95 },
    { event: "100 free", time: "55.88", confidence: 0.82 },
  ],
};

export const demoDashboardData: DashboardData = {
  user: {
    id: "demo-user",
    email: "dillon@dropsplit.dev",
    firstName: "Dillon",
    fullName: "Dillon Nagar",
  },
  swimmerProfile: {
    age: 16,
    gradeGroup: "10th grade",
    skillLevel: "intermediate",
    heightInInches: 70,
    weightLbs: 150,
    favoriteStrokes: ["Freestyle", "Backstroke"],
    bestEvents: ["50 free", "100 free", "100 back"],
    weaknesses: ["Holding stroke count late in races", "Race confidence off the blocks"],
    weeklySwimDays: 5,
    poolAccess: "School team + Saturday club lane",
    goals: ["Drop 3 seconds in the 100 free", "Get more consistent turns"],
    targetEvents: ["100 free", "50 free", "100 back"],
    currentTrainingLevel: "High school in-season with one optional Saturday practice",
    sorenessNotes: "Gets tight shoulders after two hard sprint days in a row.",
    onboardingCompleted: true,
  },
  bestTimes: [
    {
      id: "best-1",
      event: "50 free",
      course: "SCY",
      time: "25.29",
      timeSeconds: 25.29,
      date: "2026-03-26",
      note: "New practice best from push start",
    },
    {
      id: "best-2",
      event: "100 free",
      course: "SCY",
      time: "55.88",
      timeSeconds: 55.88,
      date: "2026-03-22",
      note: "Dual meet finals heat",
    },
    {
      id: "best-3",
      event: "100 back",
      course: "SCY",
      time: "1:02.14",
      timeSeconds: 62.14,
      date: "2026-03-15",
      note: "League prep meet",
    },
  ],
  weeklyPlan: {
    id: "plan-1",
    weekOf: "2026-03-23",
    totalPlannedYardage: 17800,
    targetSwimDays: 5,
    strokeFocus: "Freestyle speed endurance + backstroke underwaters",
    coachSummary:
      "This week pushes your 100 free finish speed while protecting your shoulders. Friday stays lighter so you can race well on Saturday.",
    days: [
      {
        id: "day-1",
        date: "2026-03-23",
        label: "Monday",
        focus: "Freestyle threshold",
        intensity: "hard",
        strokeFocus: "100 free pacing",
        totalYardage: 3800,
        coachNote: "Hold good posture on every turn. Quality matters more than smashing the clock on the first round.",
        completed: true,
        warmup: [
          {
            title: "Warmup",
            reps: "400 swim + 200 kick + 4 x 50 build",
            details: "Easy aerobic start, then bring the last 15 yards of each 50 up to race rhythm.",
            focus: "Bodyline and controlled breathing",
            interval: "1:00 on the 50s",
            yardage: 800,
          },
        ],
        preSet: [
          {
            title: "Pre-set",
            reps: "8 x 25",
            details: "Odds fast breakout to 12.5, evens easy backstroke.",
            focus: "Explosive first strokes",
            rest: ":20",
            yardage: 200,
          },
        ],
        mainSet: [
          {
            title: "Main set",
            reps: "3 rounds",
            details: "2 x 100 free at strong pace, 1 x 50 easy, 2 x 75 descend 1-2.",
            focus: "Feel the back-half speed without spinning",
            interval: "1:25 / 1:10 / 1:00",
            yardage: 1350,
          },
        ],
        kick: [
          {
            title: "Kick",
            reps: "6 x 50 with fins",
            details: "25 underwater kick + 25 easy swim.",
            focus: "Underwater speed",
            interval: "1:10",
            yardage: 300,
          },
        ],
        pull: [
          {
            title: "Pull",
            reps: "4 x 100 pull",
            details: "Negative split each one with paddles only if shoulders feel good.",
            focus: "Connection and catch pressure",
            interval: "1:30",
            yardage: 400,
          },
        ],
        drill: [
          {
            title: "Drill",
            reps: "6 x 50",
            details: "6-kick switch on back into smooth free.",
            focus: "Rotation timing",
            interval: "1:00",
            yardage: 300,
          },
        ],
        cooldown: [
          {
            title: "Cooldown",
            reps: "450 easy",
            details: "Mix strokes and loosen shoulders.",
            focus: "Recovery",
            yardage: 450,
          },
        ],
      },
      {
        id: "day-2",
        date: "2026-03-24",
        label: "Tuesday",
        focus: "Backstroke technique + aerobic support",
        intensity: "moderate",
        strokeFocus: "100 back turns",
        totalYardage: 3400,
        coachNote: "Keep the head still into the flags and count strokes from the same marker each round.",
        completed: true,
        warmup: [
          {
            title: "Warmup",
            reps: "600 as 200 swim / 200 pull / 200 IM drill",
            details: "Stay long and easy.",
            focus: "Range of motion",
            yardage: 600,
          },
        ],
        mainSet: [
          {
            title: "Main set",
            reps: "16 x 75",
            details: "1-4 backstroke drill/swim by 25, 5-8 aerobic back, 9-12 strong free, 13-16 choice easy/fast by 25.",
            focus: "Technique under fatigue",
            interval: "1:15",
            yardage: 1200,
          },
        ],
        kick: [
          {
            title: "Kick",
            reps: "8 x 25 vertical kick + streamline swim",
            details: "15 seconds vertical kick then sprint streamline to 15 yards.",
            focus: "Core and body tension",
            rest: ":30",
            yardage: 200,
          },
        ],
        drill: [
          {
            title: "Drill",
            reps: "6 x 50 backstroke double-arm",
            details: "Pause in streamline off every wall.",
            focus: "Shoulder timing",
            interval: "1:05",
            yardage: 300,
          },
        ],
        cooldown: [
          {
            title: "Cooldown",
            reps: "1100 easy mix",
            details: "Mostly free/back, finish with 100 easy breast.",
            focus: "Recovery volume",
            yardage: 1100,
          },
        ],
      },
      {
        id: "day-3",
        date: "2026-03-25",
        label: "Wednesday",
        focus: "Recovery and feel",
        intensity: "recovery",
        strokeFocus: "Freestyle efficiency",
        totalYardage: 2600,
        coachNote: "This is the day to come out of the water feeling better than when you got in.",
        completed: false,
        warmup: [
          {
            title: "Warmup",
            reps: "500 easy + 4 x 50 scull/swim",
            details: "Take extra easy breathing every 3 or 5 strokes.",
            focus: "Relaxed water feel",
            interval: "1:00",
            yardage: 700,
          },
        ],
        mainSet: [
          {
            title: "Main set",
            reps: "3 x (200 swim + 4 x 25 build)",
            details: "The 200s stay easy aerobic. The 25s wake your stroke up without adding fatigue.",
            focus: "Fresh speed",
            interval: "3:15 on the 200s / :40 on the 25s",
            yardage: 900,
          },
        ],
        drill: [
          {
            title: "Drill",
            reps: "8 x 50 choice drill",
            details: "2 fingertip drag, 2 single-arm, 2 zipper, 2 snorkel swim.",
            focus: "Clean hand path",
            interval: "1:05",
            yardage: 400,
          },
        ],
        cooldown: [
          {
            title: "Cooldown",
            reps: "600 easy",
            details: "Mix pull buoy and backstroke.",
            focus: "Reset shoulders",
            yardage: 600,
          },
        ],
      },
      {
        id: "day-4",
        date: "2026-03-26",
        label: "Thursday",
        focus: "Race-pace sprint",
        intensity: "hard",
        strokeFocus: "50 free speed",
        totalYardage: 3600,
        coachNote: "Fast means precise. Hit clean starts, one speed through the breakout, then own the last 15.",
        completed: false,
        warmup: [
          {
            title: "Warmup",
            reps: "400 swim + 4 x 75 kick/swim by 25 + 4 x 50 build",
            details: "Gradually raise the speed.",
            focus: "Readiness",
            interval: "1:15 on the 75s / :55 on the 50s",
            yardage: 1000,
          },
        ],
        mainSet: [
          {
            title: "Main set",
            reps: "2 rounds of 8 x 25 + 4 x 50",
            details: "25s are from a push at 50 pace with full easy recovery. 50s are smooth easy speed with perfect turns.",
            focus: "Speed without panic",
            interval: ":50 on the 25s / 1:30 on the 50s",
            yardage: 600,
          },
          {
            title: "Broken 100",
            reps: "2 x (50 + 25 + 25)",
            details: "Take :15 rest between pieces and hold goal 100 free pace.",
            focus: "Finish speed",
            yardage: 200,
          },
        ],
        kick: [
          {
            title: "Kick",
            reps: "10 x 25 flutter kick with board",
            details: "Fast to 12.5, easy in.",
            focus: "Leg speed",
            interval: ":35",
            yardage: 250,
          },
        ],
        pull: [
          {
            title: "Pull",
            reps: "4 x 100 easy pull",
            details: "Back off and recover heart rate.",
            focus: "Loosen shoulders",
            interval: "1:35",
            yardage: 400,
          },
        ],
        cooldown: [
          {
            title: "Cooldown",
            reps: "1150 easy",
            details: "Finish with 4 x 50 choice drill/swim by 25.",
            focus: "Recovery",
            yardage: 1150,
          },
        ],
      },
      {
        id: "day-5",
        date: "2026-03-27",
        label: "Friday",
        focus: "Pre-meet loosen",
        intensity: "easy",
        strokeFocus: "Starts and confidence",
        totalYardage: 2400,
        coachNote: "Leave this one hungry to race. No junk volume.",
        completed: false,
        warmup: [
          {
            title: "Warmup",
            reps: "400 easy + 4 x 50 build",
            details: "Smooth and relaxed.",
            focus: "Feel good speed",
            interval: "1:00",
            yardage: 600,
          },
        ],
        mainSet: [
          {
            title: "Main set",
            reps: "8 x 50 as 25 smooth / 25 fast",
            details: "Fast part should feel snappy, not draining.",
            focus: "Race rhythm",
            interval: "1:15",
            yardage: 400,
          },
        ],
        drill: [
          {
            title: "Drill",
            reps: "4 x 50 choice drill",
            details: "Whatever helps you feel long and quick.",
            focus: "Confidence",
            interval: "1:05",
            yardage: 200,
          },
        ],
        cooldown: [
          {
            title: "Cooldown",
            reps: "1200 easy mix",
            details: "Shake out the whole body and leave the pool feeling fresh.",
            focus: "Recovery",
            yardage: 1200,
          },
        ],
        dryland: [
          {
            title: "Optional mobility",
            reps: "8 minutes",
            details: "Band pull-aparts, shoulder circles, and calf mobility if you feel tight after school.",
            focus: "Loose shoulders and ankles",
          },
        ],
      },
    ],
  },
  recentMessages: [
    {
      id: "chat-1",
      role: "assistant",
      content:
        "Hey Dillon — your week is set up to build 100 free finish speed without frying your shoulders. Wednesday is intentionally lighter so Thursday can be sharp.",
      createdAt: "2026-03-23T15:05:00.000Z",
      suggestions: ["What should I focus on today?", "Explain Thursday's broken 100 set"],
    },
    {
      id: "chat-2",
      role: "user",
      content: "hey i swam 50 free today i got a 25.29",
      createdAt: "2026-03-26T16:40:00.000Z",
    },
    {
      id: "chat-3",
      role: "assistant",
      content:
        "Nice. 25.29 is a real step. The good sign is that you're getting speed without falling apart late. Next goal: keep that same first 25 but make the last 10 yards calmer so you don't slip water when you tighten up.",
      createdAt: "2026-03-26T16:40:30.000Z",
      loggedEntry: {
        id: "time-4",
        event: "50 free",
        course: "SCY",
        time: "25.29",
        timeSeconds: 25.29,
        date: "2026-03-26",
        context: "practice",
        source: "chat",
        confidence: 0.96,
      },
    },
  ],
  swimLogs: [
    {
      id: "log-1",
      date: "2026-03-24",
      yardage: 3400,
      durationMinutes: 82,
      type: "practice",
      sorenessLevel: 3,
      note: "Felt better on backstroke turns. Legs heavy on the last few 75s.",
      timeEntries: [
        {
          id: "time-1",
          event: "100 back",
          course: "SCY",
          time: "1:03.12",
          timeSeconds: 63.12,
          date: "2026-03-24",
          context: "practice",
          note: "Broken from push",
          source: "manual",
        },
      ],
    },
    {
      id: "log-2",
      date: "2026-03-26",
      yardage: 3600,
      durationMinutes: 85,
      type: "practice",
      sorenessLevel: 4,
      note: "Good race pace day. Need cleaner breathing pattern on fast 50s.",
      timeEntries: [
        {
          id: "time-2",
          event: "50 free",
          course: "SCY",
          time: "25.29",
          timeSeconds: 25.29,
          date: "2026-03-26",
          context: "practice",
          note: "Push start after broken 100s",
          source: "chat",
          confidence: 0.96,
        },
      ],
      uploadedFiles: [uploadedMeetSheet],
    },
    {
      id: "log-3",
      date: "2026-03-22",
      yardage: 1800,
      durationMinutes: 52,
      type: "meet",
      sorenessLevel: 2,
      note: "Dual meet. Felt calm behind the blocks.",
      timeEntries: [
        {
          id: "time-3",
          event: "100 free",
          course: "SCY",
          time: "55.88",
          timeSeconds: 55.88,
          date: "2026-03-22",
          context: "meet",
          note: "Season best",
          source: "upload",
        },
      ],
    },
  ],
  coachNotes: [
    {
      id: "note-1",
      title: "100 free finishing cue",
      body: "Think quick catch and still head position off the second turn. When you lift your head late, your hips drop and you lose speed.",
      createdAt: "2026-03-25T18:10:00.000Z",
      category: "technique",
    },
    {
      id: "note-2",
      title: "Recovery reminder",
      body: "If the shoulders still feel tight after Thursday, swap Friday paddles for easy snorkel swim and tell your real coach before the meet.",
      createdAt: "2026-03-26T06:45:00.000Z",
      category: "recovery",
    },
    {
      id: "note-3",
      title: "Race mindset",
      body: "You do not need a perfect first 15 to swim well. Get clean speed, then settle into your rhythm instead of chasing a hero start.",
      createdAt: "2026-03-26T21:05:00.000Z",
      category: "mindset",
    },
  ],
  dashboardStats: [
    { label: "This week", value: "17.8k yds", delta: "+1.4k", helper: "Planned volume" },
    { label: "Swim days", value: "5", delta: "On target", helper: "Including Saturday meet" },
    { label: "Best recent time", value: "25.29", delta: "50 free", helper: "Logged Mar 26" },
    { label: "Consistency streak", value: "11 days", delta: "+3", helper: "Pool or recovery work" },
  ],
  progressSeries: [
    { label: "Feb 10", value: 26.12 },
    { label: "Feb 24", value: 25.94 },
    { label: "Mar 3", value: 25.72 },
    { label: "Mar 17", value: 25.43 },
    { label: "Mar 26", value: 25.29 },
  ],
  frequencySeries: [
    { label: "Week 1", value: 4 },
    { label: "Week 2", value: 5 },
    { label: "Week 3", value: 4 },
    { label: "Week 4", value: 5 },
    { label: "Week 5", value: 5 },
  ],
  eventInsight: {
    title: "Lean into sprint free, keep 100 back as the secondary weapon",
    description:
      "Your sprint free is improving the fastest and you have room to gain more from starts, turns, and last-15 composure. Backstroke still gives you a strong secondary event because your underwater habits are better there.",
    primaryEvents: ["50 free", "100 free"],
    secondaryEvents: ["100 back", "200 free"],
  },
  subscription: {
    tier: "free",
    status: "free",
    messageLimit: 40,
    messagesUsed: 23,
    renewalDate: null,
  },
};

export const demoOnboardingDefaults: OnboardingInput = {
  firstName: "Dillon",
  age: 16,
  gradeGroup: "10th grade",
  skillLevel: "intermediate",
  heightInInches: 70,
  weightLbs: 150,
  favoriteStrokes: ["Freestyle", "Backstroke"],
  bestEvents: ["50 free", "100 free"],
  bestTimes: [
    { event: "50 free", time: "25.29", course: "SCY" },
    { event: "100 free", time: "55.88", course: "SCY" },
  ],
  weaknesses: ["Turns", "Holding form when tired"],
  weeklySwimDays: 5,
  poolAccess: "School team + weekend lane access",
  goals: ["Drop 3 seconds in my 100 free", "Feel more confident choosing events"],
  targetEvents: ["100 free", "50 free", "100 back"],
  currentTrainingLevel: "High school in-season",
  sorenessNotes: "Shoulders get tight if I sprint hard on back-to-back days.",
};

export function getDemoDashboardData(): DashboardData {
  return JSON.parse(JSON.stringify(demoDashboardData)) as DashboardData;
}
